name: Publish
on:
  workflow_dispatch:
    inputs:
      dryRun:
        required: true
        description: Dry run
        type: boolean
permissions:
  packages: write
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches commit history and tags
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://npm.pkg.github.com'
      - name: Configure git user
        run: |
          git config --global user.name 'Publish Bot'
          git config --global user.email 'me+bot@mattderrick.co.uk'
      - name: Install packages
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish packages
        run: ./node_modules/.bin/nx release ${{ inputs.dryRun && '--dry-run' || '' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
